### PR TITLE
Add ranking game.

### PR DESCRIPTION
**Pull request by shizejin**
Implementation of ranking game.

The performance of the code:
```Python
%timeit gt.ranking_game(100)
```

```
10000 loops, best of 3: 97.7 µs per loop
```

### CODE REVIEW

**Comment by oyamad** [comment]
Thanks. (Don't you have write permission for `oyamad/QuantEcon.py`?)

* Check your code with PEP8.
* Is the description of `steps` correct?
* Let all the `_populate_*` functions share the same return value, `None` or `payoff_arrays`. (Either is fine with me.)

**Comment by shizejin** [comment]
Yes I have the write permission. I am thinking that a PR may be convenient for review and discussion.

1. Let `_populate_*` return `None` looks more natural. I've modified my code.
2. Regarding to the description of `steps`, the paper is saying that 

    > We generated scores and costs as increasing step functions of effort with random step sizes.

    And according to the c code, `steps` is the upper bound for `randint`. Therefore, I suppose it is the
    maximal number of random step size. What do you think?

**Comment by oyamad** [comment]
1. I kept the license statement as is (other than adding `# `) intentionally violating PEP8 regarding the maximum line length.

2. Regarding the `return` statement, let's let the `_populate_*` functions share the same code literally, either with an explicit `return` or with no `return`.

3. It seems to me that the maximum step size for the cost function is `1/n`, and I think "number of steps" is always `n-1`.

**Comment by oyamad** [comment]
Yes, a PR is convenient, but it is orthogonal to whether to push commits to your repo or here; in the latter case, we could directly add commits to the PR.

**Comment by shizejin** [comment]
I see. Then should we first merge this PR and commit to your repo directly?

Regarding to `steps`, maybe the correct description should be "the maximal of random increment for each step"?

**Comment by oyamad** [comment]
Squash your commits, and push your branch `ranking_game` to `oyamad/QuantEcon.py`.

The maximum step size for the cost function seems to be not the value of `steps` but `1/n`. Is this correct?

**Comment by shizejin** [comment]
Pushed. Should I close this PR then?

Yes. I think the author intended to normalize the maximum step size for both the cost and the score functions to be `1/n`. But they don't normalize for the score function because it just functions in ordinal.

**Comment by oyamad** [comment]
Here's how I would wrote the code 6742545b6edc95fce840b3b24ad907edf9f9bb68.

One issue is that we have negative zeros:

```py
>>> g.players[0]
Player([[-0.  , -0.  , -0.  , -0.  , -0.  ],
        [ 0.82, -0.18, -0.18, -0.18, -0.18],
        [ 0.8 ,  0.8 , -0.2 , -0.2 , -0.2 ],
        [ 0.68,  0.68,  0.68, -0.32, -0.32],
        [ 0.66,  0.66,  0.66,  0.66, -0.34]])
>>> g.players[1]
Player([[ 1.  , -0.  , -0.  , -0.  , -0.  ],
        [ 0.8 ,  0.8 , -0.2 , -0.2 , -0.2 ],
        [ 0.66,  0.66,  0.66, -0.34, -0.34],
        [ 0.6 ,  0.6 ,  0.6 ,  0.6 , -0.4 ],
        [ 0.58,  0.58,  0.58,  0.58,  0.58]])
```

**Pull request closed without merging**
